// <auto-generated />
namespace ElevenNote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InitalMigraton : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalMigraton));
        
        string IMigrationMetadata.Id
        {
            get { return "202111280043550_InitalMigraton"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
